development:
  clients:
    default:
      uri: mongodb://user_game_dev:user_game_pass_dev@localhost:27017/your_app_development?authSource=admin
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: mongodb://user_game_dev:user_game_pass_dev@localhost:27017/your_app_test?authSource=admin
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5
